---
title: "EEB313 - Final Project"
output: html_notebook
---
#Needed Packages

```{r}
#Packages needed
library(tidyverse)
library(lme4)
library(lmerTest)
library(MuMIn)
library(car)
library(psych)
library(multcomp)
library(EcoSimR)
library(reshape2)
```

```{r}
Bruce <- read.csv('Bruce_Peninsula_NP_Eastern_Red-Backed_Salamander_2004-2017_data_23-02-2018.csv')
```

#Data Wrangling and Summarising

```{r}
#getting rid of French explanation of column titles
Bruce <- Bruce[-1, ]
```
```{r}
#changing counts to numnerics so it is easier to work with
Bruce$Eastern.Redback.Salamander.Count <- as.numeric(Bruce$Eastern.Redback.Salamander.Count)
Bruce$Leadback.form.of.Eastern.Redback.Salamander.Count <- as.numeric(Bruce$Leadback.form.of.Eastern.Redback.Salamander.Count)
Bruce$Redback.form.of.Eastern.Redback.Salamander.Count <- as.numeric(Bruce$Redback.form.of.Eastern.Redback.Salamander.Count)

#showing the abundance of salamanders by year
Bruce %>% 
  group_by(Year) %>% 
  summarise(count = sum(Eastern.Redback.Salamander.Count))
```
```{r}
#Average Air Temperature by year by Plot
Bruce$Air.Temperature...C. <- as.numeric(Bruce$Air.Temperature...C.)
Bruce %>%
  filter(!is.na(Air.Temperature...C.)) %>% 
  group_by(Year, Plot.Name) %>% 
  summarise(avg.air.temp = mean(Air.Temperature...C.))
```
```{r}
#Average Soil Temperature by year by Plot
Bruce$Soil.Temperature...C. <- as.numeric(Bruce$Soil.Temperature...C.)
Bruce %>% 
  filter(!is.na(Soil.Temperature...C.)) %>% 
  group_by(Year, Plot.Name) %>% 
  summarise(avg.soil.temp = mean(Soil.Temperature...C.))
```
```{r}
#making the data easy to work with
Bruce$Precipitation.in.the.Last.24.hours..mm.<- as.numeric(Bruce$Precipitation.in.the.Last.24.hours..mm.)
Bruce$Beaufort.Sky.Class <- as.numeric(Bruce$Beaufort.Sky.Class)
Bruce$Beaufort.Wind.Class <- as.numeric(Bruce$Beaufort.Wind.Class)
Bruce$Soil.Moisture <- as.numeric(Bruce$Soil.Moisture)
Bruce$Soil.pH <- as.numeric(Bruce$Soil.pH)
```

```{r}
#averaging the environmental effects over each year, grouped by plot
Bruce.summarised <- Bruce %>% 
  group_by(Year, Plot.Name) %>% 
  summarise(Salamander.pop = sum(Eastern.Redback.Salamander.Count),
            avg.air.temp = mean(Air.Temperature...C.),
            avg.soil.temp = mean(Soil.Temperature...C.),
            avg.prec.24h = mean(Precipitation.in.the.Last.24.hours..mm.),
            avg.soil.moisture = mean(Soil.Moisture),
            avg.soil.pH = mean(Soil.pH))

Bruce.summarised
```

```{r}
#making Year easier to work with
Bruce.summarised$Year <- as.numeric(as.character(Bruce.summarised$Year))

#creating a plot for salamander abundance over time, grouped by plot
Bruce.summarised %>%
  group_by(Plot.Name) %>% 
  ggplot(aes(x = Year, y = Salamander.pop, color = Plot.Name)) +
  geom_point() +
  facet_wrap(~ Plot.Name) +
  geom_smooth(method = "lm") +
  theme(legend.position = 'none') +
  ylab("Salamander Population") +
  ggtitle("Salamander Abundance: Plot Locations by Year")
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
Bruce.summarised %>%
  ggplot(aes(x = Year, y = Salamander.pop, fill = Plot.Name)) +
  geom_area() +
  ylab("Salamander Population") +
  ggtitle("Salamander Abundance on the Bruce Peninsula") +
  scale_fill_discrete(name = "Plot Name") +
  theme_minimal()
```

#Linear Model Plots for different Environmental Factors

```{r}
#model for avg soil pH and year
 Bruce.summarised %>% 
  group_by(Year, Plot.Name) %>% 
  ggplot(aes(x=Year, y= avg.soil.pH, color = Plot.Name)) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  facet_wrap(~Plot.Name) +
  ylab("Average Soil pH") +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none") +
  ggtitle("Soil pH of Bruce Peninsula : 2003 - 2017")
```

```{r}
#model for avg soil moisture and year
 Bruce.summarised %>% 
  group_by(Year, Plot.Name) %>% 
  ggplot(aes(x=Year, y= avg.soil.moisture, color = Plot.Name)) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  facet_wrap(~Plot.Name) + 
  ylab("Average Soil Moisture(%)") +
  ylim(0, 30) +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none") +
  ggtitle("Soil Mosture of Bruce Peninsula : 2003 - 2017")
```

```{r}
#model for avg precipitation and year
 Bruce.summarised %>% 
  group_by(Year, Plot.Name) %>% 
  ggplot(aes(x=Year, y= avg.prec.24h, color = Plot.Name)) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  facet_wrap(~Plot.Name) + 
  ylab("Average Precipitation: 24h (mm)") +
  ylim(0, 20) +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none") +
  ggtitle("Average Precipitation in last 24h of Bruce Peninsula : 2003 - 2017")
```

```{r}
#model for air temp and year
Bruce.summarised %>% 
  group_by(Year, Plot.Name) %>% 
  ggplot(aes(x=Year, y= avg.air.temp, color = Plot.Name)) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  facet_wrap(~Plot.Name) + 
  ylab("Average Air Temperature (F)") +
  ylim(0, 110) +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none") +
  ggtitle("Air Temperature of Bruce Peninsula : 2003 - 2017")
```
 
```{r}
#model for soil temp and year
Bruce.summarised %>% 
  group_by(Year, Plot.Name) %>% 
  ggplot(aes(x=Year, y= avg.soil.temp, color = Plot.Name)) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  facet_wrap(~Plot.Name) + 
  ylim(0, 100) +
  ylab("Average Soil Temperature (F)") +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none") +
  ggtitle("Soil Temperature of Bruce Peninsula : 2003 - 2017")
```

#Linear Models of Abundance vs. Environmental Factors

```{r}
# linear mdoel explaining count and soil temp
summary(lm(Salamander.pop ~ avg.soil.temp, data = Bruce.summarised))
```
 
```{r}
# linear model explaining count and soil pH
summary(lm(Salamander.pop ~ avg.soil.pH, data = Bruce.summarised))
```
 
```{r}
#linear model explaining count and Air temperature
summary(lm(Salamander.pop ~ avg.air.temp, data = Bruce.summarised))
```

```{r}
# linear model explaining count and Soil Moisture
summary(lm(Salamander.pop ~ avg.soil.moisture, data = Bruce.summarised))
```

```{r}
# linear model explaining count and Precipitation
summary(lm(Salamander.pop ~ avg.prec.24h, data = Bruce.summarised))
```

#Plots for Environmental Factors vs. Abundance

```{r}
#Soil Temperature vs. Abundance
Bruce.summarised %>% 
  group_by(Year, Plot.Name) %>% 
  ggplot(aes(y=Salamander.pop, x= avg.soil.temp, color = Plot.Name)) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  facet_wrap(~Plot.Name) + 
  xlab("Average Soil Temperature (F)") +
  ylab("Salamander Population Size") +
  ylim(0, 600) +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none") +
  ggtitle("Soil Temperature vs. Salamander Abundance")
```

```{r}
#Soil Moisture vs. Abundance
Bruce.summarised %>% 
  group_by(Year, Plot.Name) %>% 
  ggplot(aes(y=Salamander.pop, x= avg.soil.moisture, color = Plot.Name)) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  facet_wrap(~Plot.Name) + 
  xlab("Average Soil Moisture (%)") +
  ylab("Salamander Population Size") +
  ylim(0, 600) +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none") +
  ggtitle("Soil Moisture vs. Salamander Abundance")
```

```{r}
#Soil pH vs. Abundance
Bruce.summarised %>% 
  group_by(Year, Plot.Name) %>% 
  ggplot(aes(y=Salamander.pop, x= avg.soil.pH, color = Plot.Name)) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  facet_wrap(~Plot.Name) + 
  xlab("Average Soil pH") +
  ylab("Salamander Population Size") +
  ylim(0, 600) +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none") +
  ggtitle("Soil pH vs. Salamander Abundance")
```

```{r}
#Air Temperature vs. Abundance
Bruce.summarised %>% 
  group_by(Year, Plot.Name) %>% 
  ggplot(aes(y=Salamander.pop, x= avg.air.temp, color = Plot.Name)) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  facet_wrap(~Plot.Name) + 
  xlab("Average Air Temperature (F)") +
  ylab("Salamander Population Size") +
  ylim(0, 600) +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none") +
  ggtitle("Air Temperature vs. Salamander Abundance")
```

```{r}
#Precipitation vs. Abundance
Bruce.summarised %>% 
  group_by(Year, Plot.Name) %>% 
  ggplot(aes(y=Salamander.pop, x= avg.prec.24h, color = Plot.Name)) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  facet_wrap(~Plot.Name) + 
  xlab("Average Precipitation in last 24h (mm)") +
  ylab("Salamander Population Size") +
  ylim(0, 600) +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none") +
  ggtitle("Precipitation vs. Salamander Abundance")
```

#Model Selection for Bruce

```{r}
#Saturated Model
saturated_bruce <- lmer(Salamander.pop ~ avg.air.temp+avg.soil.temp+avg.prec.24h+avg.soil.moisture+avg.soil.pH + (1|Plot.Name), REML = TRUE, data = Bruce.summarised)
summary(saturated_bruce)
```

```{r}
#compiling a list of potential 'best' models
options(na.action = 'na.fail')
Bruce_dredge <- dredge(saturated_bruce, beta = F, evaluate = T, rank = AICc)
options(na.action = 'na.omit')
head(Bruce_dredge)
nrow(Bruce_dredge)
```
```{r}
#extracting all relevant models from the dredge
summary(model.avg(Bruce_dredge, subset = delta <= 2))
```
```{r}
#observing the top model
top_bruce <- get.models(Bruce_dredge, subset = 1)[[1]]
summary(top_bruce)
```

```{r}
#finding R squared for the top model
r.squaredGLMM(top_bruce)
```

```{r}
ggplot(Bruce.summarised, aes(x = Year, y = Salamander.pop, color = Plot.Name)) +
  geom_point(size = 3) +
  geom_line(aes(y = predict(top_bruce)), size = 1)
```
